### ISSUE TITLE
making pangeo/base-notebook compatible with stock jupyterhub

### ISSUE THREAD

**Issue by phaustin** [pangeo-data/pangeo-docker-images#112]
We'd like to adapt https://github.com/pangeo-data/pangeo-docker-images for vanilla jupyterhub deployments for research and teaching, and need a little guidance on how to make pangeo/base-notebook:latest work with dockerspawner and jupyterhub/jupyterhub:master.  Specifically, this works on localhost:  https://github.com/phaustin/jupyterhub_basics/tree/master/examples/simple

i.e.  `docker-compose up` brings up a jupyterhub on `localhost:8000` and spawns new notebooks.

but swapping scipy-notebook for pangeo/base-notebook:

https://github.com/phaustin/jupyterhub_basics/compare/pangeo

and rerunning gives the following error:

```
# 500 : Internal Server Error

Error in Authenticator.pre_spawn_start: TypeError unsupported operand type(s) for +: 'NoneType' and 'list'

You can try restarting your server from the [home page](http://localhost:8000/hub/home).
```

Any idea what dockerspawner is looking for here?

**Comment by rabernat** [comment]
Just wanted to chime in and say that I love the idea of making these docker images broadly useful, beyond our specific cloud deployments.

**Comment by phaustin** [comment]
If we could get this capability, it would definitely boost our effort to produce jupyter-books for pangeo that can be read by users with docker and a single `docker compose up` as described here:  https://github.com/executablebooks/jupyter-book/issues/765
(per my discussion with @robfatland)

**Comment by phaustin** [comment]
Got around to reading the docs:  https://jupyterhub-dockerspawner.readthedocs.io/en/latest/docker-image.html#how-to-build-your-own-docker-image

and tried the simplest thing possible and it worked:  https://github.com/phaustin/jupyterhub_basics/blob/pangeo/examples/simple/notebook_image/Dockerfile

Congratulations everyone -- having things "just work" hasn't happened to me before in my docker journey.

**Comment by yuvipanda** [comment]
That's great, @phaustin! You shouldn't need to make a new image, I made [a PR](https://github.com/phaustin/jupyterhub_basics/pull/2) that hopefully should remove the need for that :)

**Comment by phaustin** [comment]
thanks @yuvipanda -- pretty disorienting when the news keeps getting better ;-)

**Comment by phaustin** [comment]
related to #94 -- base-image has an implicit dependence on bokeh, in that the Dockerfile will fail if the bokeh static folder isn't present.  My hack to get around this, plus adding conda to the bashrc is in PR #126
