### ISSUE TITLE
Document packages in built environment.

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-docker-images#123]
It'd be nice to have a page listing all the packages included in each environment for each tag.

Essentially take the output of "Export full conda environment" from https://github.com/pangeo-data/pangeo-docker-images/runs/1049306128?check_suite_focus=true and put it somewhere easier to find.

**Comment by scottyhq** [comment]
previously these got pushed to a github pages website (https://pangeo-data.github.io/pangeo-stacks/). 

seems simpler to not have a website to keep track of too. how about just adding a column to the readme table with a link either:
1. have pangeo-bot commit a simple `packages.txt` along with `conda-linux-64.lock` under each image folder
1. commit the lists front and center in separate 'packages' branch (but still link in `master` branch readme

**Comment by scottyhq** [comment]
>  have pangeo-bot commit a simple packages.txt along with conda-linux-64.lock under each image folder

#128 implemented this 

for example: https://github.com/pangeo-data/pangeo-docker-images/blob/master/pangeo-notebook/packages.txt
