### ISSUE TITLE
update a package (not adding it)

### ISSUE THREAD

**Issue by chiaral** [pangeo-data/pangeo-docker-images#150]
Hello all, 

based on [this issue](https://github.com/dask/gcsfs/issues/299#issuecomment-716819049) writing to zarr it's not working - I could actually write a random file, but then it didn't work again, so clearly it's not a stable set up.

I did read these [instructions](http://pangeo.io/cloud.html#software-environment) about how to add a package. I am not sure how it works to update a version of the packages (the yml file does not have pinned versions, so I assume whatever version is currently in the image is because of the last time it was updated and all the dependencies were solved). 

So how do I trigger an update of a package? Also - I would definitely test it first on staging, but right now it seems that write to zarr is problematic.

**Comment by chiaral** [comment]
I should add - the problem is not writing to zarr but (based on my limited understanding)  the mapping to the cloud bucket. Anyways - it seems like I need to update the fsspec to the version suggested by Martin.

**Comment by scottyhq** [comment]
hi @chiaral looks like you need fsspec>0.8.4, you can see that is already in the pangeo-notebook image after 2020.10.16

(https://github.com/pangeo-data/pangeo-docker-images/blob/2020.10.16/pangeo-notebook/packages.txt)
https://github.com/pangeo-data/pangeo-docker-images/blob/e650d67fca4c8cae80eeb775276214d759c6b8d5/pangeo-notebook/packages.txt#L107

But https://us-central1-b.gcp.pangeo.io is running an older image `2020.10.08` (https://github.com/pangeo-data/pangeo-cloud-federation/blob/491635be3146029103dcc339bbf2aff56b515252/deployments/gcp-uscentral1b/image/binder/Dockerfile#L1)

You can either run `conda install fsspec=0.8.4` from a terminal, or log into https://staging.us-central1-b.gcp.pangeo.io, which is running a newer Docker image (https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/gcp-uscentral1b/image/binder/Dockerfile)

@TomAugspurger , maybe you want to bump staging --> prod? Maybe we should add the Docker image date to the table in the readme here https://github.com/pangeo-data/pangeo-cloud-federation ...

**Comment by chiaral** [comment]
thanks so much! I will try it out on staging and report back!

**Comment by chiaral** [comment]
everything is working wrt fsspec on staging. thanks!

**Comment by TomAugspurger** [comment]
We just deployed prod, so it'll hopefully work there as well now.
