### ISSUE TITLE
Thanks! (and a question ;-) )

### ISSUE THREAD

**Issue by jerowe** [pangeo-data/pangeo-docker-images#170]
Thanks for the great project! I really liked the way you organized the docker images, especially the use of the `onbuild` in Dockerfiles and I'm totally stealing your great ideas to build oodles of bioinformatics-related images over[ here.](https://github.com/Dabble-of-DevOps-Bio/dabble-of-devops-bioinformatics-jhub-docker) 

This isn't an issue, just a question, but I was wondering what does this line do in the start scripts?

```
#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====

export PANGEO_ENV="ml-notebook"
if ! [[ -z "${PANGEO_SCRATCH_PREFIX}" ]] && ! [[ -z "${JUPYTERHUB_USER}" ]]; then
    export PANGEO_SCRATCH="${PANGEO_SCRATCH_PREFIX}/${JUPYTERHUB_USER}/"
fi

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
```

Since all the notebook environments get named notebook?

**Comment by TomAugspurger** [comment]
Do you mean the part about PANGEO_SCRATCH? On our pangeo hubs, we let users write to a scratch bucket on GCS / S3. See https://github.com/pangeo-data/pangeo-cloud-federation/pull/637/files <https://github.com/pangeo-data/pangeo-cloud-federation/pull/637/files>.

The check here lets us just define the prefix (which differs by cloud) but reuse the image on both AWS and GCP deployments.

**Comment by jerowe** [comment]
Oh alright, I get it now. It's just something local to you guys. I was wondering if it had something to do with the conda env, but then I realized they are all called 'notebook' within the container anyways. Thanks!
