### ISSUE TITLE
2021.04.05 production release

### ISSUE THREAD

**Issue by jrbourbeau** [pangeo-data/pangeo-docker-images#201]
I'm not totally sure when release tags should be manually added. But looking through some of the recent tags, it appears when the `pangeo-notebook` conda meta-package version has been updated a corresponding `git` tag has been added. Given this, I was wondering if https://github.com/pangeo-data/pangeo-docker-images/commit/aadc1aabbff2bff9a08e4f85f5962849bf6135a8, which bumped the `pangeo-notebook` conda package to `2021.04.05`, should have a `2021.04.05` git tag as well?

**Comment by scottyhq** [comment]
> I'm not totally sure when release tags should be manually added. 

The original idea was to manually test out 'master' or 'sha' tags first via binder to catch issues around dask labextension and other things that are hard to test programmatically. Then 'calver' and 'latest' tags as production releases, so the metapackage and calver tags don't always match. but we could modify the github action to add a tag when we bump metapackage versions https://github.com/pangeo-data/pangeo-docker-images/blob/master/.github/workflows/Publish.yml 

I'll create a new tag manually for now

**Comment by jrbourbeau** [comment]
Thanks @scottyhq! Closing
