### ISSUE TITLE
rise: here or in metapackage

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-docker-images#209]
I would like to add [rise](https://rise.readthedocs.io/en/stable/) to all our hubs / binders. Since this is a jupyter-related package, would it make sense to add it here, or in the [metapackage](https://github.com/conda-forge/pangeo-notebook-feedstock)?

**Comment by scottyhq** [comment]
The original idea with the pangeo-notebook metapackages was to bundle the *minimal* set of packages needed for a functioning pangeo user interface (so key UI things for jupyterhub and dask-gateway). So maybe here? I don't have strong preferences.

**Comment by scottyhq** [comment]
closed by #256
