### ISSUE TITLE
xesmf not importing required shapely library not found

### ISSUE THREAD

**Issue by NickMortimer** [pangeo-data/pangeo-docker-images#215]
Hi I'm running latest docker image using singularity on HPC trying to get xesmf working. 

I've looked at https://github.com/pangeo-data/pangeo-docker-images/issues/101#issue-659759048 but this seems different
`import xesmf `

gives

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-7ec3550bcfad> in <module>
----> 1 import xesmf

~/.local/lib/python3.8/site-packages/xesmf/__init__.py in <module>
      1 # flake8: noqa
      2 
----> 3 from . import data, util
      4 from .frontend import Regridder, SpatialAverager
      5 

~/.local/lib/python3.8/site-packages/xesmf/util.py in <module>
      3 import numpy as np
      4 import xarray as xr
----> 5 from shapely.geometry import MultiPolygon, Polygon
      6 
      7 

~/.local/lib/python3.8/site-packages/shapely/geometry/__init__.py in <module>
      2 """
      3 
----> 4 from .base import CAP_STYLE, JOIN_STYLE
      5 from .geo import box, shape, asShape, mapping
      6 from .point import Point, asPoint

~/.local/lib/python3.8/site-packages/shapely/geometry/base.py in <module>
     17 
     18 from shapely.affinity import affine_transform
---> 19 from shapely.coords import CoordinateSequence
     20 from shapely.errors import WKBReadingError, WKTReadingError
     21 from shapely.geos import WKBWriter, WKTWriter

~/.local/lib/python3.8/site-packages/shapely/coords.py in <module>
      6 from ctypes import byref, c_double, c_uint
      7 
----> 8 from shapely.geos import lgeos
      9 from shapely.topology import Validating
     10 

~/.local/lib/python3.8/site-packages/shapely/geos.py in <module>
     90         'libc.musl-x86_64.so.1'
     91     ]
---> 92     free = load_dll('c', fallbacks=c_alt_paths).free
     93     free.argtypes = [c_void_p]
     94     free.restype = None

~/.local/lib/python3.8/site-packages/shapely/geos.py in load_dll(libname, fallbacks, mode)
     58     else:
     59         # No shared library was loaded. Raise OSError.
---> 60         raise OSError(
     61             "Could not find lib {} or load any of its variants {}.".format(
     62                 libname, fallbacks or []))

OSError: Could not find lib c or load any of its variants ['libc.musl-x86_64.so.1'].
```

**Comment by TomAugspurger** [comment]
I see that `xesmf` is in your `~/.local` directory. If you use the version in the conda env (`pip uninstall -y xesmf`) do things work? 

If that works, then it seems you've hit on some of the limitations mentioned in https://pangeo.io/cloud#your-home-directory.

**Comment by NickMortimer** [comment]
All I've done is build a clean docker container using singularity and run on hpc

 `singularity  build pangeo-custom.sif docker://pangeo/pangeo-notebook:master`

Then run the container  I've checked that I don't have this package installed in my HPC environment. 

if I pip uninstall -y xesmf I get the same result still going to local. I'm new to docker and singularity so I could well be doing something wrong.

**Comment by TomAugspurger** [comment]
I've never used singularity, so I can't say whether that's relevant.

Do you get the exact same error after pip uninstalling xesfm? It'd be
strange for it to still pick up a file in `~/.local`. Oh, looking at your
full traceback, everything is in `~/.local`. What does `which python` give,
and is there anything in `/srv/conda/envs`? The pangeo-notebook environment
should be in `/srv/conda/envs/notebook`.

**Comment by NickMortimer** [comment]
@TomAugspurger Ok so it was my inexperience with singularity, it's adding my local python path to the container, a great help but also something to be managed!

**Comment by ricardobarroslourenco** [comment]
@NickMortimer , in the end, _were you able to convert this docker image to a Singularity one_? Just curious, because I am currently working on building a Pangeo Singularity container, but it would be interesting to see if a docker conversion is already on.
