### ISSUE TITLE
Installing aws cli version 2 and/or its dependency for the `help` subcommand

### ISSUE THREAD

**Issue by consideRatio** [pangeo-data/pangeo-docker-images#216]
Using an image built `FROM pangeo/pangeo-notebook:2021.05.15` I'm using the `aws` CLI.

1. I wonder if you think we should install version 2 of the CLI (curl, unzip, :scream:, move on filesystem, done, :nauseated_face:).
2. I also wonder if you think we should install `groff` (an apt package). Apparently it is a dependency to run `help` sub-commands of like `aws s3 help` but `groff` isn't available by default in the `pangeo-notebook` image.

### Example output with `aws` CLI v1 trying to use `help` sub-command

```
$ aws
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: command



$ aws help

Could not find executable named "groff"
```

**Comment by scottyhq** [comment]
> I wonder if you think we should install version 2 of the CLI and groff

sure! feel free to open a PR for this @consideRatio . I think having the recommended CLI tools for GCP, Azure, and AWS is helpful and they don't take up too much space I think.

**Comment by consideRatio** [comment]
I found that this issue still exists in the latest images, and that `groff` is an formal requirement based on the official install instructions:

![image](https://user-images.githubusercontent.com/3837114/179349454-6ed0747c-9396-402f-8c18-66f7d1c0bc59.png)

I'll open a PR about this.

**Comment by consideRatio** [comment]
Hmmm @scottyhq I don't understand this well enough.

There are several .apt.txt files. Should this apt package be added to all, if all of these install `awscli` via conda-forge that relies on this apt package?

.binder/apt.txt
pangeo-notebook/apt.txt
pytorch-notebook/apt.txt
ml-notebook/apt.txt
