### ISSUE TITLE
nbgitpuller hangs while syncing git repo

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-docker-images#240]
Starting from http://gallery.pangeo.io/repos/cgentemann/pangeo_ccmp/01_example-CCMP-notebook.html

I opened this binder link: https://binder.pangeo.io/v2/gh/pangeo-gallery/default-binder/master/?urlpath=git-pull?repo=https://github.com/cgentemann/pangeo_ccmp%26amp%3Burlpath=lab/tree/pangeo_ccmp/01_example-CCMP-notebook.ipynb%3Fautodecode

The binder loaded up okay, but then got stuck on this url
https://hub.binder.pangeo.io/user/pangeo-gallery-default-binder-qst1k5p6/git-pull?repo=https://github.com/cgentemann/pangeo_ccmp&amp;urlpath=lab/tree/pangeo_ccmp/01_example-CCMP-notebook.ipynb?autodecode

With this status
![image](https://user-images.githubusercontent.com/1197350/129580410-ce25a6d0-9732-4cac-83a5-ce19fe34ca23.png)

The "click to see more details" button had no information.

It has been like that for 10 minutes.

I tried the same nbgitpuller link in https://staging.us-central1-b.gcp.pangeo.io/ and it worked fine.

**Comment by TomAugspurger** [comment]
The pinned nbgitpuller looks pretty old: https://github.com/pangeo-data/pangeo-docker-images/blob/2eef21daa9d399e41cbc276cd43622f5264ebb1f/base-notebook/conda-linux-64.lock#L185.

That apparently comes from the pin all the way in https://github.com/conda-forge/pangeo-notebook-feedstock/blob/84482c763e2034e76e6911e123a8b312a22ce7dd/recipe/meta.yaml#L19. I'd recommend bumping that (and maybe figuring out why it's not being auto-bumped)

**Comment by rabernat** [comment]
Thanks a lot for the tip Tom! Is it safe to just manually bump that up to a newer version, or could I create an incompatibility problem that way? What would you recommend I try?

**Comment by rabernat** [comment]
Confirming that upgrading nbgitpuller works in docker!

```
docker run -it --rm --volume `pwd`:/pangeo-forge -p 8888:8888 pangeo/pangeo-notebook:latest /bin/bash -c "mamba install --yes -n notebook -c conda-forge rise ipytree nbgitpuller==1.0.2; jupyter lab --ip 0.0.0.0 /pangeo-forge"
```

**Comment by TomAugspurger** [comment]
Manually bumping for now seems OK to me. Actually https://github.com/conda-forge/pangeo-notebook-feedstock/pull/84 is open with a bump, so maybe we just merge that?

**Comment by TomAugspurger** [comment]
https://github.com/conda-forge/pangeo-notebook-feedstock/pull/84 is merged now. I think that a bot will update the environment files here soon.

**Comment by rabernat** [comment]
Amazing Tom, thanks so much!

While I've got you here, can I get you to review https://github.com/conda-forge/pangeo-notebook-feedstock/pull/86? (All related to the same project.) I don't want to break anything.

**Comment by weiji14** [comment]
Not sure if this is still relevant since we've removed the pangeo binder links a few months ago already (https://github.com/pangeo-data/pangeo-docker-images/issues/459). Either way, `nbgitpuller` is at version [1.2.0](https://github.com/pangeo-data/pangeo-docker-images/blob/a736179ff9636278175122c669f93afce959637b/pangeo-notebook/packages.txt#L399), so I'll assume this is 'fixed' and close this.
