### ISSUE TITLE
geo util packages

### ISSUE THREAD

**Issue by raybellwaves** [pangeo-data/pangeo-docker-images#242]
I recently gave an xarray talk and was looking to use the docker image here.

The reqs for my talk are at https://github.com/raybellwaves/PyData-Portland-2021-talk/blob/main/env.yml

I noticed in https://github.com/pangeo-data/pangeo-docker-images/blob/master/base-notebook/packages.txt

it's missing:
 - geopy
 - timezonefinder

These could be added

**Comment by rabernat** [comment]
Great suggestion! PR welcome! 

https://github.com/pangeo-data/pangeo-docker-images/blob/master/pangeo-notebook/environment.yml
