### ISSUE TITLE
`requirements.txt` `stackstac` overwrites the `rasterio` conda package with a pip package. This eliminates the support for HDF4 format.

### ISSUE THREAD

**Issue by BnJam** [pangeo-data/pangeo-docker-images#248]
Conda installs `rasterio-1.1.8` which is the full binary with HDF4 support. Pip installs `stackstac` which has a dependency for `rasterio==1.2.6` that overwrites the Conda package and replaces it with the pip package elimating the HDF4 format support. 

Tags affects: 2021.05.15 and onward.

**Comment by TomAugspurger** [comment]
Looks like stackstac is in conda-forge now: https://github.com/conda-forge/stackstac-feedstock

Would you be able to make a PR moving it from requirements.txt to the environment.yaml?
