### ISSUE TITLE
Real Time Collaboration

### ISSUE THREAD

**Issue by betolink** [pangeo-data/pangeo-docker-images#270]
Is there a way to enable the real time collaboration if I'm using the base image?

https://jupyterlab.readthedocs.io/en/stable/user/rtc.html

Maybe overriding the start entry point to add the `--collaborative` flag?

**Comment by scottyhq** [comment]
@betolink agreed this is a neat feature. I assume you mean using one of these images in a JupyterHub context, and I'm pretty sure that has to be set via JupyterHub/DaskHub helm chart configuration... Pinging @consideRatio and @sgibson91 who might be able to point to the right docs describing how this could be done.

**Comment by betolink** [comment]
Thanks Scott, looks like it's possible but the hub needs to be configured a bit differently. See: https://github.com/2i2c-org/infrastructure/issues/810#issuecomment-972602602

**Comment by consideRatio** [comment]
Z2JH based config:

```yaml
singleuser:
  cmd:
    - jupyterhub-singleuser
    - --LabApp.collaborative=True
```

General JupyterHub config:

```python
c.Spawner.cmd = ["jupyterhub-singleuser" ,"--LabApp.collaborative=True"]
```

Note you may also want to install jupyterlab-link-share extension for a button in the JupyterLab UI for users to use, depending on your setup, it may or may not work for it to fetch a token that grants other access via link sharing.

**Comment by consideRatio** [comment]
Sounds resolved, close issue?

**Comment by betolink** [comment]
Thanks for the guidance, just for future reference it would probably be useful to mention that real time collaboration can be enabled for Pangeo deployments.

**Comment by consideRatio** [comment]
I agree, not sure where to document this though without it being written in too many separate places which we end up failing to maintain if something changes.
