### ISSUE TITLE
Add Git-LFS?

### ISSUE THREAD

**Issue by willirath** [pangeo-data/pangeo-docker-images#278]
I'm often using LFS even for moderately large (dozens of MB) data files. Just noticed that the pangeo-notebook image does not include it.

I'll open a PR, but would like to have an opinion whether this should go to the `apt.txt` (and hence use git-lfs from the OS) or to the conda env definition (and hence use git-lfs from conda-forge).

**Comment by scottyhq** [comment]
i've found that `git` from conda-forge tends to be a much more recent version compared to what you get from `apt`, so the same is probably true of `git-lfs`. 

I think the preference should be use conda-forge. ideally we could get rid of apt.txt altogether to have few configuration levels and files. 

Feel free to open a PR for this @willirath !
