### ISSUE TITLE
stackstac

### ISSUE THREAD

**Issue by BnJam** [pangeo-data/pangeo-docker-images#286]
https://github.com/gjoseph92/stackstac/issues/83 is now closed - can `stackstac` be included in the `environment.yml` now for pangeo-notebook?

**Comment by BnJam** [comment]
Excellent! Thank you for the quick work! 

Can this be integrated with the 2022.01.31 build or will it have to live in the next one?

**Comment by scottyhq** [comment]
@BnJam stackstac is in `pangeo-notebook:2022.02.04`: https://github.com/pangeo-data/pangeo-docker-images/blob/66015a25e0029dc95d6367349d91b74e844a9bc0/pangeo-notebook/packages.txt#L527
