### ISSUE TITLE
ML notebook tests failing (installing pytest on top of environment)

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-docker-images#294]
` docker run -u 1000 -w /srv/test -v $PWD:/srv/test ${DOCKER_ORG}/ml-notebook:PR ./run_tests.sh ml-notebook` Runs the following to install pytest in the image and run a few simple tests, but the conda environment solving isn't working in  #289 `Determining conflicts:...`

```
# --no-channel-priority added b/c solver failing installing into ml-notebook
conda install pytest --freeze-installed --no-channel-priority
```

https://github.com/pangeo-data/pangeo-docker-images/runs/5412813529?check_suite_focus=true 

Some solutions:

1. `pip install pytest --no-deps` 
2. We could also switch github actions to use the repo2docker github action
https://github.com/jupyterhub/repo2docker-action/pull/83

**Comment by yuvipanda** [comment]
Since the testing is also done after everything is built, I'd suggest trying to install it with pip. I do want to add enough features to repo2docker-action so it can be used here...

**Comment by scottyhq** [comment]
closed by https://github.com/pangeo-data/pangeo-docker-images/pull/289/commits/fcbbac56eb6e93620442f6e893c265278e9e6921
