### ISSUE TITLE
ML notebook versions tightly pinned

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-docker-images#302]
As of image 2022.04.15:

https://github.com/pangeo-data/pangeo-docker-images/blob/793b4d01621e1f3177991313044059f7506481cf/ml-notebook/environment.yml#L7-L10 

Discussion in the PR https://github.com/pangeo-data/pangeo-docker-images/pull/300 , but opening an issue to note this in case somebody wants to figure out how to increase compatible versions of jax, jaxlib, and tensorflow

**Comment by ngam** [comment]
This should be generally be fixed on the conda-forge side for recent versions. The issue from the discussion seems to be the convoluted versioning the jax team follows (to facilitate better development, they iterate the simpler jax a lot more than they iterate the heavier and more complicated jaxlib, so the versioning can be quite hard to understand, but credit to them, they have thorough documentation on this: https://jax.readthedocs.io/en/latest/design_notes/jax_versioning.html)
