### ISSUE TITLE
Add pop-tools package to environment

### ISSUE THREAD

**Issue by shanicetbailey** [pangeo-data/pangeo-docker-images#317]
Hi, 

Can someone add `pop-tools` to the cloud environment please? Currently I am doing a mamba install every time I want to run a nb with the package.

Here is the info on pop-tools if that's relevant for the issue: https://github.com/NCAR/pop-tools.
Thanks!

**Comment by rabernat** [comment]
Hi Shanice! I've transferred this issue to pangeo-docker-images.

You can propose the change yourself by adding it to this file and making a PR: https://github.com/pangeo-data/pangeo-docker-images/blob/master/pangeo-notebook/environment.yml

🚀

**Comment by shanicetbailey** [comment]
Great, thank you! I made a PR.

**Comment by scottyhq** [comment]
closed by #318
