### ISSUE TITLE
What to call this repository?

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-docker-images#32]
@TomAugspurger @rabernat @tjcrone @jhamman @rsignell-usgs @ocefpaf Now that this repository is starting to get some use, what should we call it? 

1) rename this to `pangeo-stacks` and move the existing pangeo-stacks to `pangeo-stacks-archive`?
2) call this `pangeo-docker-images`
3) something else?

**Comment by tjcrone** [comment]
If I'm not mistaken, the "pangeo-stacks" name was meant to evoke the idea/structure of [jupyter-stacks](https://github.com/jupyter/docker-stacks). I like this, and I would be okay keeping pangeo-stacks, but I also like the idea of naming the repo something even more helpful and descriptive, like pangeo-docker-images. I think I'm leaning toward the latter, but my feeling-level is somewhat middling.

**Comment by rsignell-usgs** [comment]
I like `pangeo-docker-images` too.   Easier to grasp for new folks who don't know or care about Jupyter development!

**Comment by scottyhq** [comment]
Thanks for the feedback just renamed it to pangeo-docker-images. seems better to settle on sooner rather than later as we setup bots for CI.
