### ISSUE TITLE
'parcels' package brings in a lot of heft with Qt dependency

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-docker-images#329]
Packages that depend on 'matplotlib' rather that 'matplotlib-base' bring in Qt, which as far as i know is mainly for desktop backends rather than jupyterlab. This inflates the image size by hundreds of MB:

docker run --rm -it condaforge/mambaforge:latest /bin/bash
```
docker run --rm -it condaforge/mambaforge:latest /bin/bash
mamba create -n matplotlib matplotlib

  Install: 119 packages
  Total download: 342MB

docker run --rm -it condaforge/mambaforge:latest /bin/bash
mamba create -n matplotlib-base matplotlib-base
  Install: 67 packages
  Total download: 134MB

313M	/opt/conda/envs/matplotlib-base/
1.1G   /opt/conda/envs/matplotlib/
```

I'll open an issue over in parcels to see if they can switch to 'matplotlib-base'...

```
jovyan@2085a748e0b0:~$ conda-tree whoneeds qt -t --small 
qt==5.12.9
  ├─ pyqtchart 5.12 [required: >=5.12.9,<5.13.0a0]
  │  └─ pyqt 5.12.3 [required: 5.12, py39h0fcd23e_8]
  │     └─ matplotlib 3.5.2 [required: any]
  │        └─ parcels 2.3.0 [required: >=2.0.2]
```

**Comment by rabernat** [comment]
Thanks for finding this Scott! It's a very important package for some oceanographers. Thanks for offering to open the issue. I bet they can manage with the matplotlib-base dependency. I looked at the repo but couldn't even figure out where the dependencies are specified.

**Comment by scottyhq** [comment]
Yes, trying to do a little cleanup by looking at the largest dependencies. FYI parcels is the also the only package brings in gcc (Total download: 113MB). So @rabernat if you're familiar with the package and think that also could be eliminated (I'm surprised this would be a run-time dependency?) I bet we could shave nearly 1 GB off these images! 

```
jovyan@2085a748e0b0:~$ conda-tree whoneeds gcc_linux-64 -t --small 
gcc_linux-64==11.2.0
  └─ parcels 2.3.0 [required: any]
```

**Comment by erikvansebille** [comment]
Thanks @scottyhq, for checking this. Indeed, it seems that matplotlib-base works well for parcels too, I've now opened a PR to fix this: https://github.com/OceanParcels/parcels/pull/1174/ Note that we will also need to change the file at https://github.com/conda-forge/parcels-feedstock/blob/main/recipe/meta.yaml, but I'd rather do that after we've merged the PR

As for `gcc`: parcels does need a C-compiler because of the Just-in-Time kernel compilation that is at the heart of parcels. @ckehl may know much more whether we could do with a smaller package than the full gcc; perhaps he can comment?

**Comment by CKehl** [comment]
Hi @all - short feedback, more to come.

For jit, this package is mandatory and it must must come from conda-forge. Reason is that the gcc package from conda-forge is completely transitional and allows for equal compilation of the kernel with the same compiler flags on all platforms (i.e. Win, Mac, Unix). The anaconda package for gcc, for example, is platform-dependent and thus some flags we require for the compilation wouldn't work on MacOS (testd - fails CI on MacOS). Reason: the whole interpolation code is included in a header file (parcels.h). This is, under normal rulebase of C and gcc, non-compliant and thus not allowed - source code goes in a source file. So, for ease of development and compilation, we don't comply with the strict rules for C99/C11 and thus we need _that_ specific package from _that_ specific channel.

"No JIT, no gcc" - dubious. Thing is that all kernel code is pushed through the kernel generator (have a look at `parcels/kernels/basekernel.py`), and that kernel generator mandates imports of ctypes and so forth. It's just that the _actual_ C-code generation is only done in JIT mode. It's possible to make that non-mandatory, but it would require a major overhaul of the background engine to disentangle the kernel interpretation from ctypes. Just to clearify. the kernel generator does more than just calling `gcc` - it also enforces that the function signature of the function given as kernel complies with the signature `ret func(particle, fieldset, time)` and that this function only contains code that _can_ be interpreted in-full as a kernel. This is just an information for consideration.

For more details, I am available via mail, MS Teams, etc. - or reply to this post. Happy to give feedback on it.

**Comment by weiji14** [comment]
Looks like `matplotlib` has been removed from the `pangeo-notebook` image, with just `matplotlib-base` remaining after commit e5356d7d4e67ca84b70e706fc7c4dff181b84101/#333. The image is currently using [`parcels=2.4.2`](https://github.com/pangeo-data/pangeo-docker-images/blame/f3e2c2d6a3b4992f5269b2d95966a6544db63b37/pangeo-notebook/packages.txt#L424) for reference, and that includes the patch from https://github.com/erikvansebille/parcels-feedstock/pull/4. Closing as done.
