### ISSUE TITLE
Bump to Python 3.10

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-docker-images#332]
It's been out for a while and 3.11 is on the horizon. I suspect most packages are now available on conda-forge 
https://peps.python.org/pep-0602/

**Comment by rabernat** [comment]
Correct, beam does not yet support python 3.10

> This is the first github repository i've seen with 'issues' disabled !

That's how most apache-incubated projects do it. Their issue trackers are in Jira: https://issues.apache.org/jira/projects/BEAM

**Comment by scottyhq** [comment]
looks like github is now being used and we're waiting on https://github.com/apache/beam/pull/17700 

would be nice to update as 3.11 is right around the corner (https://peps.python.org/pep-0664/)
