### ISSUE TITLE
ml-notebook does not have the 'SCRATCH_BUCKET' and does not produce link to right dask dashboard

### ISSUE THREAD

**Issue by dhruvbalwada** [pangeo-data/pangeo-docker-images#386]
I noticed two things in the ml-notebook that are different from the regular notebook.

1. The environment variable 'SCRATCH_BUCKET', which on the m2lines deployment is set as 'gcs://m2lines-scratch/dhruvbalwada' does not exist. 
2. The dask dashboard is not properly configured, when I do 
```
import distributed

client = distributed.Client()
client
``` 
I get the dashboard link  http://127.0.0.1:46197/status, which not accessible on the cloud. It should instead be something like: https://m2lines.2i2c.cloud/user/dhruvbalwada/proxy/8787/status. 

I don't know how or where these things are being set.

**Comment by dhruvbalwada** [comment]
@yuvipanda - I think this two-part issue might be in your wheel house too.

**Comment by scottyhq** [comment]
@dhruvbalwada those are JupyterHub configuration settings so I think you'll want to open 2 separate issues here https://github.com/2i2c-org/infrastructure for the m2lines Hub
