### ISSUE TITLE
Using jax in ml-notebook instantly kills kernel

### ISSUE THREAD

**Issue by dhruvbalwada** [pangeo-data/pangeo-docker-images#387]
I am trying to use jax on the ml-notebook, but run into the problem that even the most basic functions kill the kernel. 

If I run the following code (first 4 lines from the [jax tutorial](https://jax.readthedocs.io/en/latest/notebooks/quickstart.html)): 
```
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random

key = random.PRNGKey(0)
```

I get the error that kernel is restarting. I am using the m2lines deployment.

Since, I don't even know what the error is, I am not sure who is the person to reach out to about this. I will tag @jmunroe from 2i2c, as his team is most well-versed in this hub.

**Comment by dhruvbalwada** [comment]
I was able to figure out that this issue has something to do with ptxas, but not sure how to address this. Here is a screenshot: 
![Screen Shot 2022-10-12 at 9 20 29 AM](https://user-images.githubusercontent.com/18236610/195353723-6c19fcee-7b86-4a47-91a4-fcb0e22ef5f9.png)

**Comment by rabernat** [comment]
Thanks for digging into this Dhruv! @ngam - any thoughts on what might be wrong here?

**Comment by rabernat** [comment]
The information is here: https://github.com/2i2c-org/infrastructure/blob/63a034530f30179bc80313126624cc337836e744/config/clusters/m2lines/common.values.yaml#L94-L97

It's `pangeo/ml-notebook:2022.09.21`.

**Comment by rabernat** [comment]
Dhruv, it looks like the `pangeo/ml-notebook:2022.09.21` predates #378, which might resolve the issue. I'm going to try that on https://staging.leap.2i2c.cloud/ and see if it works.

**Comment by rabernat** [comment]
I was unable to overwrite the ML image using the configurator, so I haven't gotten an answer yet.

**Comment by dhruvbalwada** [comment]
Thank you so much ngam!

**Comment by yuvipanda** [comment]
On the cluster, we follow https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#installing_drivers to install the drivers. We use the 'default' version here. The m2lines hub is on k8s 1.21 and hence is running driver version R450 (whatever that means?!). We can upgrade that to 'latest' if needed.

**Comment by dhruvbalwada** [comment]
@ngam - I tried downgrading the cuda-nvcc (after some updates to the cloud deployment, it was at 11.8.X). However that did not solve the problem - sadly.

**Comment by dhruvbalwada** [comment]
Maybe helpful, I was reading this https://github.com/google/jax/issues/5723 . It said have the 
nvcc --version (right now on 11.6, after downgrading from 11.8)and 
nvidia-smi (right now on 11.0). 
be on the same version.

**Comment by dhruvbalwada** [comment]
@ngam setting xla flags as you and the error message suggested did work. 

It comes with the downside, as quoted :
```
2022-10-12 19:37:48.587389: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_asm_compiler.cc:61] cuLinkAddData fails. This is usually caused by stale driver version.
2022-10-12 19:37:48.587444: E external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:1363] The CUDA linking API did not work. Please use XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1 to bypass it, but expect to get longer compilation time due to the lack of multi-threading.
```
However, since I am new to all this, it is unlikely to a bottle neck to anything I am doing for now.

**Comment by dhruvbalwada** [comment]
Thank you @ngam !!! 
This is a great fix for now. Will report more if there are problems. 

Maybe @yuvipanda  will resolve the version issue, or solve https://github.com/2i2c-org/infrastructure/issues/1765 (maybe better long term solution that trying to get the K80s to work?)

**Comment by yuvipanda** [comment]
@dhruvbalwada ok, so T4 is now available in https://staging.m2lines.2i2c.cloud/, with clearer options too. So you can try that out now.

**Comment by dhruvbalwada** [comment]
Thank you @yuvipanda! Will give that a try. For now, I don't have access to staging on m2lines - can you authorize that?

**Comment by yuvipanda** [comment]
@dhruvbalwada try now?

**Comment by dhruvbalwada** [comment]
Still same error 403 : Forbidden. Does it take few minutes to propogate?

**Comment by yuvipanda** [comment]
@dhruvbalwada hmm, nope. I think it's something to do with GitHub org membership. I've just instead deployed it to m2lines prod - can you try it out at  m2lines.2i2c.cloud?

**Comment by dhruvbalwada** [comment]
Awesome, yes I see it. Will report back on results soon.

**Comment by dhruvbalwada** [comment]
@yuvipanda - I tried the T4. It does not resolve the problem, maybe as the version numbers are still distinct (nvcc at 11.8 and nvidia-smi at 11.0). 
As discussed above we can bypass this problem by turning off multi-threading inside python. 

Maybe the version numbers need to be pinned? @ngam do you have suggestions for what to do with a working T4?

**Comment by yuvipanda** [comment]
@dhruvbalwada ok, i'm going to try changing the driver version now, so let's see.

**Comment by yuvipanda** [comment]
@dhruvbalwada Try restarting your server, you should see cuda version 11.4 now?

**Comment by dhruvbalwada** [comment]
I see cuda version 11.4 and nvcc version 11.8.89. The XLARuntimeError still shows up.  :( 
@ngam - do you have any suggestions for specific version numbers that might solve??

**Comment by dhruvbalwada** [comment]
So what did work for me now, is this. 
I downgraded the nvcc to 11.4. This fixed the problem. Should we pin this for now?

**Comment by dhruvbalwada** [comment]
Unless it is possible to take CUDA all the way upto 11.8 (without breaking anything else)?

**Comment by yuvipanda** [comment]
@dhruvbalwada I'll have to upgrade the k8s master, and then upgrade the nodes to make that up I think. Should be doable without interruption, am trying that out now. Will keep you posted here.

**Comment by yuvipanda** [comment]
I think it would be very useful to have a table of cuda versions and the pangeo docker images they are compatible with.

**Comment by dhruvbalwada** [comment]
I don't know how to get that. I also am not sure what other things (apart from JAX) are relying on the cuda versions.

**Comment by yuvipanda** [comment]
@dhruvbalwada you're gonna see a couple minutes interruption on m2lines now, sorry about that.

**Comment by dhruvbalwada** [comment]
No worries, I am not doing anything of significance at the moment. Kill the instance if you have to.

**Comment by yuvipanda** [comment]
@dhruvbalwada ok, killed :)

**Comment by yuvipanda** [comment]
Now at:

```
(notebook) jovyan@jupyter-yuvipanda:~$ nvidia-smi
Wed Oct 12 22:38:45 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

@dhruvbalwada @ngam I think 11.6 is as high as GKE is gonna go for now.

**Comment by dhruvbalwada** [comment]
As predicted by ngam: 

On T4: 
- Downgrading to nvcc-11.6 (matching to CUDA) makes things work. 

On K80
- Downgrading to nvcc-11.6 (matching to CUDA) **does not** make things work.
- Bypassing and turning off multi-threading works. 
```
import os
os.environ["XLA_FLAGS"]="--xla_gpu_force_compilation_parallelism=1"
```

**Comment by dhruvbalwada** [comment]
@ngam - should we pin nvcc to 11.6 for now (so that the user doesn't have to manually downgrade everytime)?

**Comment by dhruvbalwada** [comment]
Thank you. I think we can close this issue when the PR is merged.

**Comment by dhruvbalwada** [comment]
Open again
