### ISSUE TITLE
Update dask to 2022.9.2

### ISSUE THREAD

**Issue by dhruvbalwada** [pangeo-data/pangeo-docker-images#388]
How would we go about updating dask to the 2022.9.2 version? 

This version is supposed to fix a major problem that many run into with using dask: https://github.com/dask/distributed/discussions/7128#discussioncomment-3859002. 

Do @jbusecke or @TomNicholas know how to do the update?

**Comment by jrbourbeau** [comment]
I believe there are bots that automatically handle updating packages. https://github.com/pangeo-data/pangeo-docker-images/pull/385 (opened 4 days ago) updates, among other things, `dask` + `distributed` to `2022.9.2`. @scottyhq does CI passing on that PR mean the package updates are okay, or is there further testing that's usually done?

**Comment by jbusecke** [comment]
Big +1 from me. I would love to check out the 'worker-saturation' feature on the hubs too!

**Comment by yuvipanda** [comment]
@jbusecke https://github.com/2i2c-org/infrastructure/pull/1769 is the equivalent on the hubs.

**Comment by scottyhq** [comment]
> does CI passing on that PR mean the package updates are okay, or is there further testing that's usually done? 

Yes. no further testing is done currently. But I do usually look over the PR diff to make sure there are no major package version drops and look at the actions log to make sure the image size doesn't change significantly. It would be awesome to add some automated checks for those things! and @yuvipanda i wonder if it's now a good time to revive the idea of automated testing of new images on the hub itself with a bot user (I know there has been discussion of this in the past)...

**Comment by scottyhq** [comment]
closed by #385
