### ISSUE TITLE
Images availability for OS/ARCH other than linux/amd64

### ISSUE THREAD

**Issue by j34ni** [pangeo-data/pangeo-docker-images#396]
@scottyhq 

I would like to use your docker images (in particular pangeo/pangeo-notebook and pangeo/ml-notebook) on an IBM POWER9 machine and I was wondering if there was any plan to make these available for linux/ppc64le?

**Comment by scottyhq** [comment]
> I was wondering if there was any plan to make these available for linux/ppc64le 

Unfortunately, there is no plan for that. We only support and test `linux/amd64`, mainly because that is the main cloud architecture available for the Pangeo-supported JupyterHubs these images are designed for.

That said, I'd be interested to hear how it goes if anybody does put some time into building these images for other platforms! https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/

**Comment by j34ni** [comment]
@scottyhq 

That is a shame, because beside this POWER9 machine I was planing to run these images on ARM-based machines (and I guess that others may also be interested)

I started to rebuild with `buildx build --platform=linux/ppc64le` and that seems to work for the `base-image`
The only changes I had to make to the Dockerfile were `FROM ppc64le/ubuntu:22.04` and `Mambaforge-Linux-ppc64le.sh`

However the `pangeo-notebook` failed at 
``` 
=> ERROR [7/1] RUN echo "Checking for pip 'requirements.txt'..."                     
```
Any idea about how I should adapt that?

**Comment by yuvipanda** [comment]
I do think we should provide ARM builds though :D

**Comment by scottyhq** [comment]
There are two parts for this, and I suggest starting without docker and just getting a conda environment for your architecture:

1) Do the conda packages exist (either cross-platform or platform-specific)
2) If yes, build a docker image that encapsulates that conda environment

I quickly tried re-creating the pangeo-notebook environment on AWS (`c6g.medium` -> `amazon/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-20220912`) with no luck because of various packages that I suspect have compiled dependencies:

```
wget https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-aarch64.sh  
bash Mambaforge-Linux-aarch64.sh  
mamba env create --file https://raw.githubusercontent.com/pangeo-data/pangeo-docker-images/master/pangeo-notebook/environment.yml
```

```
Encountered problems while solving:
  - nothing provides requested ciso
  - nothing provides requested esmpy
  - nothing provides requested parcels
  - nothing provides requested xcape
  - nothing provides esmpy needed by xesmf-0.1.2-py_0
  - nothing provides pykdtree needed by satpy-0.10.0-pyh326bf55_0
```

**Comment by j34ni** [comment]
The very same packages are also missing for the `linux/ppc64le` architecture

**Comment by yuvipanda** [comment]
https://github.com/pangeo-data/pangeo-docker-images/pull/399 should remove the only hardcoding of amd64 in the dockerfiles. After this, images can be built to run arm64 / ppc46le once conda-forge has all the packages required for them.

**Comment by yuvipanda** [comment]
Apparently I got nerdsniped by this, and #399 now implements most of what is needed in this repo. Based on #399, here is the list of packages so far that need to be supported in conda-forge:

## pangeo-notebook

### Both `arm64` and `ppc64le`

- [ ] ciso
- [ ] esmpy
- [ ] parcels
- [ ] xscape
- [ ] pykdtree
- [ ] h5py

### `ppce64le` only

- [ ]tiledb-py

## ML Notebook (Tensorflow)

Both `arm64` and `ppc64le`

- [ ] tensorflow
- [ ] jaxlib

## PyTorch Notebook

Both `arm64` and `ppc64le`

- [ ] pytorch
- [ ] torchvision

## Forge Image

Both `arm64` and `ppc64le`

- [ ] apache-beam-with-gcp

Once these are done, #399 should work and we can then add the setup required to build multi-arch images. I think we should definitely support arm64, although I'm not sure about ppc64le. In particular, does this mean if we try to add a new package in the future but it doesn't support ppc64le, we don't add it?

**Comment by yuvipanda** [comment]
I don't have any conda-forge experience so I can't really work on these. If someone else does and gets all these packages working, please ping me here again and I'll try get #399 to completion.

**Comment by yuvipanda** [comment]
@ngam yeah, hence I think ARM is more likely than PPC64. I think there are significant cloud cost savings to be had with ARM...

**Comment by yuvipanda** [comment]
@ngam tensorflow already supports aarch64 (see https://pypi.org/project/tensorflow/2.10.0/#files for wheel), and so does torch https://pypi.org/project/torch/#files. jaxlib supports arm64 macos but not an aarch64 wheel (https://pypi.org/project/jaxlib/0.3.22/#files) but i suspect that shouldn't be too much work?

**Comment by yuvipanda** [comment]
@ngam here is the error I get for h5py when making ppc64le:

```
  - package h5py-2.10.0-mpi_mpich_py36he791a77_6 requires python_abi 3.6.* *_cp36m, but none of the providers can be installed
```

**Comment by yuvipanda** [comment]
@ngam okkkk i made a PR https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3533

**Comment by yuvipanda** [comment]
@ngam it is just from `conda-lock`, I ran:

```
cd pangeo-notebook
conda-lock lock --mamba -k explicit -f environment.yml -f ../pangeo-notebook/environment.yml -f ../base-notebook/environment.yml  -p linux-ppc64le
```

**Comment by j34ni** [comment]
> The pangeo-notebook image should be doable though.

This is the image we use most, so that would be a great start

**Comment by j34ni** [comment]
> For now I simply commented the lines of the environment related to missing ppc64el packages and the build still fails

I eventually got it built, the error was due to the presence in the same directory of the `conda-linux-64.lock` file .

I guess that this would not happen if there was no hard-coded CPU architecture in the Dockerfiles

**Comment by j34ni** [comment]
> Which ones are these? Same as above? I have just merged the PR for `pykdtree`. So that can be taken out of the list.

Yes, it is:

~~ciso~~
esmpy
parcels
tiledb-py
xcape
xesmf
~~pykdtree~~

**Comment by j34ni** [comment]
It seems OK for ciso and pykdtree, but there is now pyresample >=1.10.3 (also needed by satpy) which is missing
So I still comment satpy

**Comment by scottyhq** [comment]
Just wanted to revive this discussion in case people are motivated for pushing on package availability on other systems. It looks like `win-64` is also an issue for some of the same packages:

```
Could not lock the environment for platform win-64
Could not solve for environment specs
Encountered problems while solving:
  - nothing provides requested esmpy
  - nothing provides requested xcape
  - nothing provides esmpy needed by xesmf-0.1.2-py_0
```

**Comment by weiji14** [comment]
Jun 2023 update. Tried running the following for aarch64:

```
cd pangeo-notebook/
conda-lock lock -f environment.yml -f ../pangeo-notebook/environment.yml -f ../base-notebook/environment.yml -p linux-aarch64
```
and it looks like only 2 packages in `pangeo-notebook` are not working on aarch64:

```
Could not solve for environment specs
The following packages are incompatible
├─ parcels   does not exist (perhaps a typo or a missing channel);
└─ satpy   is uninstallable because there are no viable options
   ├─ satpy [0.10.0|0.11.0|...|0.42.2] would require
   │  └─ pyresample >=1.10.3 , which does not exist (perhaps a missing channel);
   └─ satpy [0.9.0|0.9.1|0.9.2|0.9.3|0.9.4] would require
      └─ pyresample >=1.10.0 , which does not exist (perhaps a missing channel).
```

- [ ] parcels, see https://github.com/conda-forge/parcels-feedstock/pull/95#issuecomment-1580828263 and PR at https://github.com/conda-forge/parcels-feedstock/pull/96
- [ ] pyresample which is a dependency of satpy, need to open a PR to add `pyresample` to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/arch_rebuild.txt.

**Comment by weiji14** [comment]
Thanks @ngam for getting those last packages over the finish line for `linux-aarch64`! I just tried locking `pangeo-notebook` and it worked :tada: Pytorch and tensorflow doesn't seem ready yet, but we can work on those later.

Shall we revive @yuvipanda's PR at #399 to add in `linux-aarch64` first for `pangeo-notebook` only?

**Comment by yuvipanda** [comment]
yay amazing, that would be great, @weiji14

**Comment by scottyhq** [comment]
I'm motivated to see this through now that I'm having to use `osx-arm64`. The only two packages that are incompatible are `ciso` and `xcape`:

```
Could not solve for environment specs
The following packages are incompatible
├─ ciso does not exist (perhaps a typo or a missing channel);
└─ xcape does not exist (perhaps a typo or a missing channel).
```

**Comment by weiji14** [comment]
I'm tempted to drop `xcape` since it's also incompatible with Python 3.12 builds, and I haven't seen any activity at https://github.com/conda-forge/xcape-feedstock/pull/22. For `ciso`, we can open up a migration for `osx-arm64` by adding it to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt.

**Comment by scottyhq** [comment]
Just documenting that Docker Desktop 4.30.0 on `osx-arm64` will currently run `docker run -it pangeo/base-notebook:latest /bin/bash` with the following caveats:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Image may have poor performance, or fail, if run via emulation
```

**Comment by weiji14** [comment]
Ok, we've got `osx-64`, `osx-arm64` and `linux-aarch64` builds for `base-notebook` and `pangeo-notebook` now (see tag [`2024.06.28`](https://github.com/pangeo-data/pangeo-docker-images/releases/tag/2024.06.28)) :tada:

Just circling back to the original request for `linux/ppc64le` images, I think we should be able to set things up for `base-notebook`. Getting a build for `pangeo-notebook` would require tiledb-py to have a ppc64le build, and `ml-notebook` might be tricky because of JaX (see https://github.com/google/jax/issues/4493, and need to wait for https://github.com/conda-forge/jaxlib-feedstock/pull/253). Question is how far do we want to support ppc64le? Up to `pangeo-notebook`, or `ml-notebook`/`pytorch-notebook` too?

**Comment by weiji14** [comment]
The `tiledb-py` ppc64le build PR just got merged at https://github.com/conda-forge/tiledb-py-feedstock/pull/251, so we might be able to try this out for `pangeo-notebook` now!
