### ISSUE TITLE
Prefect pinned in pangeo-notebook

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-docker-images#410]
https://github.com/pangeo-data/pangeo-docker-images/blob/2e6d92f01e959ad2a5cc224e5090023dab81d828/pangeo-notebook/environment.yml#L64

It'd be nice to remove explicit pins as much as possible in the environment definitions, and I think prefect is only really used in the pangeo-forge image anyways. @yuvipanda @cisaacstern is this pin even necessary anymore? can we move prefect to just the forge image?

**Comment by yuvipanda** [comment]
It's not used in pangeo-forge anymore, so if it isn't used anywhere else we can actually remove it

**Comment by weiji14** [comment]
I've deleted and recreated the `conda-lock.yml` files in #465 for the `forge` image so that `prefect` isn't included anymore. We can close this issue once that PR is merged.

**Comment by weiji14** [comment]
Should be ok to close this now that #465 is merged with `prefect` being purged from the `conda-lock.yml` files.

P.S. @scottyhq, I've happy to get added to this repo's team if you need help closing down stale issues and general maintenance stuff :smile:

**Comment by scottyhq** [comment]
> P.S. @scottyhq, I've happy to get added to this repo's team if you need help closing down stale issues and general maintenance stuff 

Thanks @weiji14, just added you as a maintainer!
