### ISSUE TITLE
What is the procedure to request a new tag?

### ISSUE THREAD

**Issue by jbusecke** [pangeo-data/pangeo-docker-images#421]
Thanks for merging #419 so quickly! I believe to get this new image we need to add a tag (and then I need to trigger an update with 2i2c on our side). Is there a formal procedure for this? Or can I just ask here to add a tag `2023.01.03`?

**Comment by scottyhq** [comment]
There isn't any formal procedure.  Anyone with admin access to the repository can push date tags to match a given commit (currently the "pangeo-admin" team) but happy to add others who want to work on this repository.

The original idea was to manually use images on staging hubs for a bit to make sure things work beyond what is currently tested, and then add a date tag to use on production hubs. In practice that hasn't happened, and I've just been adding a new tag once every couple of weeks...

In any case, just added `2023.01.03`!
