### ISSUE TITLE
pin bokeh<3

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-docker-images#425]
As heard on the pangeo weekly call, bokeh=3 breaks the holoviz stuff, so we should be pinning
` bokeh<3` in our environments.   Maybe this is being handled by a metapackage but I couldn't find it.

**Comment by weiji14** [comment]
Bokeh was updated from 2.4.3 to 3.1.0 in https://github.com/pangeo-data/pangeo-docker-images/commit/2e05fb483fedb2f3b05be6ffa7fb8db44af9ca4a/#452, and it looks to be working fine? Currently we're using `bokeh=3.1.1` in the main branch, see https://github.com/pangeo-data/pangeo-docker-images/blame/f3e2c2d6a3b4992f5269b2d95966a6544db63b37/base-notebook/packages.txt#L36

Closing now, but feel free to reopen if there's any issues!
