### ISSUE TITLE
Safari issues with "2023.06.20"

### ISSUE THREAD

**Issue by jbusecke** [pangeo-data/pangeo-docker-images#466]
**Describe the bug**
We just [updated to "2023.06.20"](https://github.com/2i2c-org/infrastructure/pull/2733) over at LEAP, and I am now unable to open a jupyterhub terminal window on safari. 

**To Reproduce**
Open "File > New > Terminal Window"

**Docker Image Version (e.g. quay.io/pangeo/ml-notebook:2023.06.20):**

**Infrastructure (Where you are running this image):**
- Pangeo JupyterHub (https://us-central1-b.gcp.pangeo.io)
- LEAP-Pangeo JupyterHub (leap.2i2c.cloud)

**Screenshots**
<img width="503" alt="image" src="https://github.com/pangeo-data/pangeo-docker-images/assets/14314623/d6689c3a-4ceb-4318-bafd-4ab9e5dbb0db">

**Additional context**
It seems that a newer version of safari might fix this, and it works on chrome, but I just wanted to document this.

**Comment by jbusecke** [comment]
Similar as in #467, this does not occur with `pangeo:pangeo-notebook:2023.05.18`

**Comment by weiji14** [comment]
Does this issue still appear with newer tags like `pangeo-notebook:2023.09.19`?

**Comment by weiji14** [comment]
Assuming that this is working again, since LEAP has updated to `pangeo-notebook:2024.01.23` at https://github.com/2i2c-org/infrastructure/pull/3688. Feel free to reopen if this is still an issue.

**Comment by jbusecke** [comment]
Nope havent seen this again. Thanks.
