### ISSUE TITLE
Dask Dashboard link not working on ml specific images

### ISSUE THREAD

**Issue by jbusecke** [pangeo-data/pangeo-docker-images#471]
**Describe the bug**
I am having trouble displaying the dask dashboard for a Local Cluster on the LEAP hub (leap.2i2c.cloud) for either one of the ML specific images  (`pytorch-notebook` and `ml-notebook`)

**To Reproduce**
If I do:
```
from distributed import Client
client = Client()
client
```

I get this (as expected):
<img width="636" alt="image" src="https://github.com/pangeo-data/pangeo-docker-images/assets/14314623/01aa9f7c-0851-4994-ba62-b3bc127e78e6">

But when I follow the link to the dashboard I am getting a 404:
<img width="649" alt="image" src="https://github.com/pangeo-data/pangeo-docker-images/assets/14314623/12c1f41e-c77d-40d1-993e-fa50849faa52">

This seems to occur only with the ML specific images  (`pytorch-notebook` and `ml-notebook`) image (tested on several different node types on the LEAP hub).
The `pangeo-notebook` works as expected. I wonder if there is a dependency issue with dask/distributed and the extra ML libraries.

**Docker Image Version (e.g. quay.io/pangeo/ml-notebook:2023.02.27):**
Error reproduced on:
- pangeo/ml-notebook:2023.05.18
- pangeo/pytorch-notebook:2023.05.18
- pangeo/pytorch-notebook:ebeb9dd

pangeo/pangeo-notebook:2023.05.18 works as expected

**Infrastructure (Where you are running this image):**
- other JupyterHub (leap.2i2c.cloud)

**Comment by yuvipanda** [comment]
@jbusecke I think this is most likely due to dask-labextension not working with jupyterlab 4 https://github.com/dask/dask-labextension/pull/263

**Comment by weiji14** [comment]
Similar to https://github.com/pangeo-data/pangeo-docker-images/issues/467#issuecomment-1726951897, can we close this issue now that `dask-labextension` 7.0.0 is installed? https://github.com/pangeo-data/pangeo-docker-images/blob/a736179ff9636278175122c669f93afce959637b/ml-notebook/packages.txt#L120

**Comment by weiji14** [comment]
Ok, just tried running `docker run -it --rm --gpus all -p 8888:8888 -p 8787:8787 quay.io/pangeo/ml-notebook:2023.09.25 jupyter lab --ip 0.0.0.0` and the dask dashboard code above. Visited the dashboard at `http://127.0.0.1:8787/status` and it looks fine, so closing.

![image](https://github.com/pangeo-data/pangeo-docker-images/assets/23487320/42709368-23e6-4a0b-a729-6e017168d320)
