### ISSUE TITLE
Support anywidget / lonboard

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-docker-images#520]
I'd love to be able to use anywidget / lonboard in our Pangeo hubs.

It looks like this requires a customized installation in the base jupyterhub image: https://github.com/manzt/anywidget/issues/385#issuecomment-1821263446

**Comment by manzt** [comment]
May also be relevant/useful https://github.com/developmentseed/lonboard/issues/397

**Comment by weiji14** [comment]
From https://github.com/developmentseed/lonboard/issues/397#issuecomment-1973444749, it sounds like we just need to install `anywidget` into pangeo-docker-images, and then users should be able to install `lonboard` themselves on top? I can open a quick PR to add `anywidget` if that sounds good.

**Comment by kylebarron** [comment]
For now you still need to ensure that the server and client anywidget versions exactly match.

**Comment by weiji14** [comment]
Closed by #532.
