### ISSUE TITLE
Release with jupyterhub 4.1+

### ISSUE THREAD

**Issue by consideRatio** [pangeo-data/pangeo-docker-images#523]
JupyterHub 4.1 has been released and tested for a while, resulting in 4.1.4 and now been around without bugfixes requested for a week or so.

When `jupyterhub-singleuser` 4.1.4 is part of the image, it changes the requirements on some interactions where javascript api requests are made to the `jupyter_server`. These requirements could require updates to software like `nbgitpuller` (compatible with 1.2.1) that from a browser's view interacts with the jupyter server via javascript requests.

There could be software in these images that still needs to be made compatible with `jupyterhub-singleuser` 4.1.4, but I'm not aware of any currently.

**Comment by jhamman** [comment]
@consideRatio - should we expect any compatibility issues with `daskhub` deployments here?

**Comment by consideRatio** [comment]
2024.03.30 is released to include jupyterhub 4.1 and nbgitpuller 1.2.1 which is compatible - be on the lookout for issues related to javascript API requests to user servers or jupyterhub when used with jupyterhub - specifcally about missing XSRF tokens etc.

There is no known issue, but there could be yet to be discovered issues.

**Comment by consideRatio** [comment]
Ping @scottyhq for visibility - jupyterhub 4.1.4 is used in 2024.03.30 now - which could bring xsrf issues and require updates in misc packages, for example nbgitpuller which is already patched, when using this image in a as a jupyterhub user server.
