### ISSUE TITLE
Confusion about numpy version in 2024.07.30 release

### ISSUE THREAD

**Issue by jbusecke** [pangeo-data/pangeo-docker-images#570]
Hey everyone, 

I just looked into the latest release to see if this one already had numpy 2.0. 

Looking at https://github.com/pangeo-data/pangeo-docker-images/blob/77b90e0a0a27389e181c7d207af5fdb852035973/base-notebook/conda-linux-64.lock#L218 I thought this was the case, but when I pull the image on the LEAP Jupyterhub using a [custom image](https://leap-stc.github.io/leap-pangeo/jupyterhub.html#custom-images) and putting in `quay.io/pangeo/pangeo-notebook:2024.07.30`, and then run

```python
import numpy as np
np.__version__
```

I get '1.26.4' 🙃. 

Am I looking in the wrong spot to verify the versions?

**Comment by scottyhq** [comment]
The lock file you've linked to is for the `base-notebook`, but it looks like you're pulling the `pangeo-notebook`. I recomment looking at packages.txt in each subfolder for the packages versions, so:

https://github.com/pangeo-data/pangeo-docker-images/blob/77b90e0a0a27389e181c7d207af5fdb852035973/pangeo-notebook/packages.txt#L465

**Comment by scottyhq** [comment]
The following packages in pangeo-notebook are requiring numpy<2 (`conda-tree whoneeds numpy -t --small | grep "<2"`)
```
  ├─ geocube 0.6.0 [required: >=1.20,<2]
  ├─ numba 0.60.0 [required: >=1.22.3,<2.1]
  │  ├─ stackstac 0.5.0 [required: <2.0.0,>=1.3.0]
  ├─ tiledb-py 0.30.1 [required: >=1.26.4,<2.0a0]
  ├─ xclim 0.51.0 [required: >=1.20.0,<2.0.0]
```

**Comment by jbusecke** [comment]
Ah thanks for the detail @scottyhq! This is very useful to know.
