### ISSUE TITLE
Can we install editors such as nano?

### ISSUE THREAD

**Issue by yutianwuldeo** [pangeo-data/pangeo-docker-images#576]
It seems like in the default environment editor vi is available for use. Would it be possible to install another editor nano, which is easier to use? Thanks very much for considering my request! 

Yutian Wu

**Comment by scottyhq** [comment]
Hi @yutianwuldeo, thanks for raising this question. Unfortunately we don't have clear-cut guidelines for what to include and what not to :( 

Are you using these images on the Pangeo JupyterHub or on your own infrastructure? You can always fork this repository to create customized images. I'd be curious to know how much extra space adding `nano` takes? 

It looks like it is available from conda-forge, so you can either add it for a particular image (e.g. pangeo-notebook):
https://github.com/pangeo-data/pangeo-docker-images/blob/master/pangeo-notebook/apt.txt

Or for all images:
https://github.com/pangeo-data/pangeo-docker-images/blob/4552cca5fcd4377ca3a6806f7cc7ef33d96abd63/base-notebook/environment.yml#L5-L8

**Comment by mdsumner** [comment]
about 0.5 Mb looking at the footprint on my ubuntu

also vote for this, nano is a lifesaver

**Comment by scottyhq** [comment]
Nano is now in pangeo-notebook [2024.10.11](https://github.com/pangeo-data/pangeo-docker-images/releases/tag/2024.10.11) and later
