### ISSUE TITLE
datatree now missing in 2024.10.11

### ISSUE THREAD

**Issue by dhruvbalwada** [pangeo-data/pangeo-docker-images#587]
**Describe the bug**
datatree is missing in the release: https://github.com/pangeo-data/pangeo-docker-images/releases/tag/2024.10.11 

It seems that datatree is not available in this release now. This may be partly related to the fact that datatree got merged into xarray (https://github.com/pydata/xarray/discussions/9680). 
However, this latest xarray release is not part of the current image. 

**Infrastructure (Where you are running this image):**
- leap.2i2c.cloud (@jbusecke is the owner)

**Comment by jbusecke** [comment]
Thanks for raising this @dhruvbalwada. @scottyhq can we issue a new release here (which should include the new xarray)?

**Comment by scottyhq** [comment]
>  @scottyhq can we issue a new release here (which should include the new xarray) 

The release process is just to add a new tag is just `git tag 2024.10.26` and `git push --tags`, which I just did, so hopefully it's fixed. @jbusecke in the future I think you have rights to do this?

**Comment by jbusecke** [comment]
I seem to be able to issue a release from the gh interface, so maybe? Sorry I never checked for this.
