### ISSUE TITLE
Missing Bottleneck package on new gcp-uscentral1b

### ISSUE THREAD

**Issue by chiaral** [pangeo-data/pangeo-docker-images#87]
Hello, 

I started playing with the new pangeo server. 
I started running an old script and I got this error:

```
ModuleNotFoundError: No module named 'bottleneck'
```

my script uses bfill()

In fact, if I go on a new notebook and try 

`import bottleneck as bn`
I get
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-d82a72844dfa> in <module>
----> 1 import bottleneck as bn

ModuleNotFoundError: No module named 'bottleneck'
```

I just thought to report it. 
thanks so much!

**Comment by TomAugspurger** [comment]
Adding that seems reasonable. It would go in
https://github.com/pangeo-data/pangeo-docker-images/blob/master/pangeo-notebook/environment.yml
.

**Comment by chiaral** [comment]
that would be great - I will follow this issue for updates on when it is merged.

**Comment by scottyhq** [comment]
bottleneck is now in `pangeo/pangeo-notebook:2020.06.30`

https://github.com/pangeo-data/pangeo-docker-images/blob/f8fd2a86eaec56fa5156bf17d419cadb486e8b26/pangeo-notebook/conda-linux-64.lock#L248

**Comment by TomAugspurger** [comment]
Thanks Scott! We'll need to manually update the image tag we use in the GCP
hub. I'll do that today as part of some other work.

**Comment by chiaral** [comment]
Just a note - I still get the error for bottleneck on staging of us-central1-b

```ModuleNotFoundError: No module named 'bottleneck'bfill ```

**Comment by TomAugspurger** [comment]
The tag in Dockerfile in pangeo-cloud-federation will need to be updated.
